language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -r travis_requirements.txt
script:
- pytest --cov RatS --cov-report term-missing
- pytest --flakes
- pytest --pep8
- pytest --mccabe -m mccabe
- pytest --pylint -m pylint
notifications:
  email:
    recipients:
    - stegschreck@gmail.com
    on_success: change
    on_failure: always
after_success: coveralls
